version: "3.3"
services:
  fuseki:
    container_name: fuseki
    build:
      context: ./fuseki
      dockerfile: Dockerfile
    command: [ "/init.sh",  "-tdb2", "--config=/fuseki/config.ttl"]
    ports:
      - 3030:3030
    volumes:
      - ./volumes/fuseki:/staging
    restart: on-failure

  middleware:
    container_name: middleware
    build: ./middleware
    command: ["java", "-jar",  "-Dspring.profiles.active=prod", "./target/back-end.jar", "production"]
    ports:
      - 8080:8080
    depends_on:
      - fuseki
    restart: on-failure
